services:
  - type: web
    name: Zoom Sentiment Analysis with Live Transcription
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    repo:  https://github.com/zoom/videosdk-LTT-sentiment-analysis
    rootDir: .
    plan: free
    envVars:
      - key: ZOOM_SDK_KEY
        sync: false
      - key: ZOOM_SDK_SECRET
        sync: false